application: gdn-gnews-alerts
version: 7
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /admin/.*
  script: admin.app
  login: admin
  secure: always
- url: /jobs/.*
  script: jobs.app
  login: admin
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest